[cfg.services.core.redis.${env}]
start = "--permanent-peer"

[cfg.services.core.hab-builder-jobsrv.${env}]
start = "--permanent-peer --bind database:redis.${env} --bind router:hab-builder-router.${env}"

[cfg.services.core.hab-builder-sessionsrv.${env}]
start = "--permanent-peer --bind database:redis.${env} --bind router:hab-builder-router.${env}"

[cfg.services.core.hab-builder-vault.${env}]
start = "--permanent-peer --bind database:redis.${env} --bind router:hab-builder-router.${env}"
